### ISSUE TITLE
Incorrect statistic being used for free space alarm

### ISSUE THREAD

**Issue by ericjsilva** [dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms#16]
Per [AWS documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-cloudwatchmetrics.html#managedomains-cloudwatchmetrics-cluster-metrics), the `Minimum` and `Maximum` metrics show the free space for a single node and `Sum` shows the free space across all nodes in the cluster.

The module should accept a variable to handle multi-node clusters and set the statistic accordingly.

https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/blob/eb23546f6ba48dae4b59e6487a87e1bc62a55d1f/alarms.tf#L64

**Comment by AndrewFarley** [comment]
@dubiety and @ericjsilva So, I believe this issue and this PR merged is actually an error folks.  I'd recommend reverting this PR immediately.  Per the AWS documentation. 

See: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html

```
FreeStorageSpace minimum is <= 20480 for 1 minute, 1 consecutive time
A node in your cluster is down to 20 GiB of free storage space. See Lack of available storage space. This value is in MiB, so rather than 20480, we recommend setting it to 25% of the storage space for each node.
```

The way they describe this "best practice" alarm is if ANY node goes below a threshold.  You will never get this from an SUM() of the disk space.  Each individual node can and will itself lock writes based on its INDIVIDUAL low disk.  This metric is NOT an aggregate-based metric that triggers errors.

I highly recommend you immediately revert this PR.  If you'd like to separately generate an sum-based alert, that's fine please go ahead and do that.  But, the MINIMUM-based alarm is CRITICAL for all deployments, because data doesn't magically go evenly to all your ES nodes.

**Comment by ericjsilva** [comment]
@AndrewFarley I agree with your analysis, and I think this could be improved with additional information in the module about how the Minimum metric actually works in a multi-node cluster.  It reports on the lowest disk size of any node in your cluster and not the overall combined space of your cluster.

For example, we have a 6 data node and 3 master node cluster. If each data node had 1TB of disk storage, you would expect your cluster to have 6TB of space and setting a free space alarm of 25% of 6TB is incorrect. You must set the alarm to 25% of 1TB or 250GB, otherwise you will get false positive alarms.

@dubiety I think the [README](https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/blob/master/README.md?plain=1#L21) and [variable description](https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/blob/master/variables.tf#L200) should be updated to add clarity.
